include:
  - local: /.gitlab/tools.yml

stages:
  - status-pre
  - image
  - test
  - status-post

# image jobs
build-image-postgres-10-branch:
  extends:
    - .build-docker
  stage: image
  except:
    - tags
  script:
    - make build-image
  variables:
    IMAGE_ARGS: --push
    IMAGE_ARCH: postgres-10

build-image-postgres-10-tag:
  extends:
    - .build-docker
  stage: image
  only:
    - tags
  script:
    - make build-image
  variables:
    IMAGE_ARGS: --push
    IMAGE_ARCH: postgres-10

build-image-postgres-11-branch:
  extends:
    - .build-docker
  stage: image
  except:
    - tags
  script:
    - make build-image
  variables:
    IMAGE_ARGS: --push
    IMAGE_ARCH: postgres-11

build-image-postgres-11-tag:
  extends:
    - .build-docker
  stage: image
  only:
    - tags
  script:
    - make build-image
  variables:
    IMAGE_ARGS: --push
    IMAGE_ARCH: postgres-11

.test-schema:
  stage: test
  script:
    - export PGHOST=localhost
    - export PGPASSWORD=test_root
    - export PGDATABASE=test_schema
    - 
      psql -c "SELECT 'ok';" || sleep 3600
    - ./scripts/schema-create.sh
    - cpan TAP::Parser::SourceHandler::pgTAP
    - pg_prove test/*.sql
  variables:
    POSTGRES_DATABASE: test_schema
    POSTGRES_PASSWORD: test_root

test-schema-postgres-10:
  extends:
    - .test-pgtap-10
    - .test-schema

test-schema-postgres-11:
  extends:
    - .test-pgtap-11
    - .test-schema

# github jobs
github-pending:
  stage: status-pre
  extends:
    - .build-curl
  script:
    - ./scripts/github-status.sh pending

github-failure:
  stage: status-post
  extends:
    - .build-curl
  when: on_failure
  script:
    - ./scripts/github-status.sh failure

github-success:
  stage: status-post
  extends:
    - .build-curl
  when: on_success
  script:
    - ./scripts/github-status.sh success
